-- Insert Types
INSERT INTO TYPECODES (ID, DESCRIPT) 
VALUES  (1, 'BOOK');
INSERT INTO TYPECODES (ID, DESCRIPT)
VALUES  (2, 'MOVIE');
INSERT INTO TYPECODES (ID, DESCRIPT)
VALUES  (3, 'TV SHOW');

-- Insert Unit of Measure
INSERT INTO UOM (ID, DESCRIPT) 
VALUES  (1, 'PAGES');
INSERT INTO UOM (ID, DESCRIPT) 
VALUES  (2, 'MINUTES');

-- Insert Genres
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Action');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Adventure');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Animation');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Chick Flick');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Children''s');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Comedy');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Crime');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Documentary');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Drama');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Fairy Tale');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Family');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Fantasy');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Fiction');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Historical Fiction');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'History');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Horror');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Musical');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Mystery');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Romance');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Science Fiction');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Stop Motion');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Thriller/Suspense');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'War');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Western');

INSERT INTO SERIES (DESCRIPT) VALUES ('Harry Potter');
INSERT INTO SERIES (DESCRIPT) VALUES ('The Lord of the Rings');
INSERT INTO SERIES (DESCRIPT) VALUES ('Star Wars');
INSERT INTO SERIES (DESCRIPT) VALUES ('Toy Story');
INSERT INTO SERIES (DESCRIPT) VALUES ('The Lion King');
INSERT INTO SERIES (DESCRIPT) VALUES ('The Hunger Games');
INSERT INTO SERIES (DESCRIPT) VALUES ('The Chronicles of Narnia');
INSERT INTO SERIES (DESCRIPT) VALUES ('Pirates of the Caribbean');
INSERT INTO SERIES (DESCRIPT) VALUES ('Fantastic Beasts');
INSERT INTO SERIES (DESCRIPT) VALUES ('How to Train Your Dragon');
INSERT INTO SERIES (DESCRIPT) VALUES ('Shrek');
INSERT INTO SERIES (DESCRIPT) VALUES ('The Incredibles');
INSERT INTO SERIES (DESCRIPT) VALUES ('Kung Fu Panda');

INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Harry Potter and the Sorcerer''s Stone', 2, 1, 1, '2001-11-16', 152, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Harry Potter and the Chamber of Secrets', 2, 1, 2, '2002-11-15', 161, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Harry Potter and the Prisoner of Azkaban', 2, 1, 3, '2004-06-04', 142, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Harry Potter and the Goblet of Fire', 2, 1, 4, '2005-11-18', 157, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Harry Potter and the Order of the Phoenix', 2, 1, 5, '2007-07-11', 138, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Harry Potter and the Half-Blood Prince', 2, 1, 6, '2009-07-15', 153, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Harry Potter and the Deathly Hallows: Part 1', 2, 1, 7, '2010-11-19', 146, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Harry Potter and the Deathly Hallows: Part 2', 2, 1, 8, '2011-07-15', 130, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('The Lord of the Rings: The Fellowship of the Ring', 2, 2, 1, '2001-12-19', 178, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('The Lord of the Rings: The Two Towers', 2, 2, 2, '2002-12-18', 179, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('The Lord of the Rings: The Return of the King', 2, 2, 3, '2003-12-17', 201, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Star Wars: Episode I – The Phantom Menace', 2, 3, 1, '1999-05-19', 136, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Star Wars: Episode II – Attack of the Clones', 2, 3, 2, '2002-05-16', 142, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Star Wars: Episode III – Revenge of the Sith', 2, 3, 3, '2005-05-19', 140, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Star Wars: Episode IV – A New Hope', 2, 3, 4, '1977-05-25', 121, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Star Wars: Episode V – The Empire Strikes Back', 2, 3, 5, '1980-05-21', 124, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Star Wars: Episode VI – Return of the Jedi', 2, 3, 6, '1983-05-25', 131, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Star Wars: Episode VII – The Force Awakens', 2, 3, 7, '2015-12-18', 138, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Star Wars: Episode VIII – The Last Jedi', 2, 3, 8, '2017-12-15', 152, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Star Wars: Episode IX – The Rise of Skywalker', 2, 3, 9, '2019-12-20', 142, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Toy Story', 2, 4, 1, '1995-11-22', 81, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Toy Story 2', 2, 4, 2, '1999-11-24', 92, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Toy Story 3', 2, 4, 3, '2010-06-18', 103, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Toy Story 4', 2, 4, 4, '2019-06-21', 100, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('The Lion King', 2, 5, 1, '1994-06-24', 88, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('The Lion King II: Simba''s Pride', 2, 5, 2, '1998-10-27', 81, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('The Lion King 1.5', 2, 5, 1.5, '2004-02-10', 77, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('The Hunger Games', 2, 6, 1, '2012-03-23', 142, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Catching Fire', 2, 6, 2, '2013-11-22', 146, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Mockingjay – Part 1', 2, 6, 3, '2014-11-21', 123, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Mockingjay – Part 2', 2, 6, 4, '2015-11-20', 137, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('The Lion, the Witch and the Wardrobe', 2, 7, 1, '2005-12-09', 143, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Prince Caspian', 2, 7, 2, '2008-05-16', 150, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('The Voyage of the Dawn Treader', 2, 7, 3, '2010-12-10', 113, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('The Curse of the Black Pearl', 2, 8, 1, '2003-07-09', 143, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Dead Man''s Chest', 2, 8, 2, '2006-07-07', 151, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('At World''s End', 2, 8, 3, '2007-05-25', 169, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('On Stranger Tides', 2, 8, 4, '2011-05-20', 137, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Dead Men Tell No Tales', 2, 8, 5, '2017-05-26', 129, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Fantastic Beasts and Where to Find Them', 2, 9, 1, '2016-11-18', 133, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('The Crimes of Grindelwald', 2, 9, 2, '2018-11-16', 134, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('The Secrets of Dumbledore', 2, 9, 3, '2022-04-15', 142, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('How to Train Your Dragon', 2, 10, 1, '2010-03-26', 98, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('How to Train Your Dragon 2', 2, 10, 2, '2014-06-13', 102, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('How to Train Your Dragon: The Hidden World', 2, 10, 3, '2019-02-22', 104, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Shrek', 2, 11, 1, '2001-05-18', 90, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Shrek 2', 2, 11, 2, '2004-05-19', 93, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Shrek the Third', 2, 11, 3, '2007-05-18', 93, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Shrek Forever After', 2, 11, 4, '2010-05-21', 93, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('The Incredibles', 2, 12, 1, '2004-11-05', 115, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Incredibles 2', 2, 12, 2, '2018-06-15', 118, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Kung Fu Panda', 2, 13, 1, '2008-06-06', 92, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Kung Fu Panda 2', 2, 13, 2, '2011-05-26', 91, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Kung Fu Panda 3', 2, 13, 3, '2016-01-29', 95, 2);
INSERT INTO ITEM (DESCRIPT, TYPEID, SERIESID, ORDERID, FIRSTRELEASE, LENGTH, UOMID) VALUES ('Kung Fu Panda 4', 2, 13, 4, '2024-03-08', 94, 2);