--DO NOT RESET TYPECODES OR ENTITY TABLE - THEY HAVE HARDCODED VALUES IN SQL QUERIES

DROP TABLE ITEM;
DROP TABLE SERIES;
DROP TABLE GENRE;
DROP TABLE ITEMGENRE;

DROP GENERATOR GEN_ITEM_ID;
DROP GENERATOR GEN_SERIES_ID;
DROP GENERATOR GEN_GENRE_ID;

CREATE SEQUENCE GEN_ITEM_ID START WITH 1 INCREMENT BY 1;
GRANT USAGE ON SEQUENCE GEN_ITEM_ID TO "PUBLIC";

CREATE SEQUENCE GEN_SERIES_ID START WITH 1 INCREMENT BY 1;
GRANT USAGE ON SEQUENCE GEN_SERIES_ID TO "PUBLIC";

CREATE SEQUENCE GEN_GENRE_ID START WITH 1 INCREMENT BY 1;
GRANT USAGE ON SEQUENCE GEN_GENRE_ID TO "PUBLIC";

CREATE TABLE ITEM (
    ID INTEGER,
    DESCRIPT VARCHAR(50) NOT NULL, --MAKE NOT NULL - ERR MESSAGE IF NULL
    TYPEID INTEGER NOT NULL, --FK TYPE TABLE
    SERIESID INTEGER, --FK SERIES TABLE
    ORDERID DOUBLE PRECISION, --CAN BE NULL, CAN BE DECIMALS (0.5 FOR PREQUEL, ETC)
    FIRSTRELEASE DATE,
    LENGTH INTEGER, --PAGES FOR BOOK, MINUTES FOR MOVIE - UI CAN TRANSLATE TO ACTUAL TIME HH:MM AS NEEDED
    UOMID INTEGER, --FK UOM TABLE - PAGES/MINUTES
    PRIMARY KEY (ID)
);

CREATE TABLE SERIES (
    ID INTEGER,
    DESCRIPT VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE GENRE (
    ID INTEGER,
    DESCRIPT VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ITEMGENRE (
    ITEMID INTEGER NOT NULL,
    GENREID INTEGER NOT NULL,
    ORDERID INTEGER,
    UNIQUE (ITEMID, GENREID)
);

SET TERM !! ;

CREATE OR ALTER TRIGGER ITEM_INSERT FOR ITEM
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_ITEM_ID,1);
END;
!!

CREATE OR ALTER TRIGGER SERIES_INSERT FOR SERIES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_SERIES_ID,1);
END;
!!

CREATE OR ALTER TRIGGER GENRE_INSERT FOR GENRE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_GENRE_ID,1);
END;
!!

SET TERM ; !!

-- Insert Genres
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Action');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Adventure');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Animation');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Chick Flick');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Children''s');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Comedy');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Crime');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Documentary');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Drama');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Fairy Tale');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Family');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Fantasy');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Fiction');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Historical Fiction');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'History');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Horror');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Musical');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Mystery');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Romance');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Science Fiction');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Stop Motion');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Thriller/Suspense');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'War');
INSERT INTO GENRE (ID, DESCRIPT) 
VALUES (GEN_ID(GEN_GENRE_ID, 1), 'Western');

