DROP TABLE AUTHOR;
DROP TABLE ENTITY;
DROP TABLE GENRE;
DROP TABLE ITEM;
DROP TABLE ITEMGENRE;
DROP TABLE PEOPLE;
DROP TABLE PLATFORM;
DROP TABLE PRODUCTION;
DROP TABLE SERIES;
DROP TABLE TYPECODES;
DROP TABLE UOM;

CREATE TABLE ITEM (
    ID INTEGER,
    DESCRIPT VARCHAR(50) NOT NULL, --MAKE NOT NULL - ERR MESSAGE IF NULL
    TYPEID INTEGER NOT NULL, --FK TYPE TABLE
    SERIESID INTEGER, --FK SERIES TABLE
    ORDERNUM DOUBLE PRECISION, --CAN BE NULL, CAN BE DECIMALS (0.5 FOR PREQUEL, ETC)
    FIRSTRELEASE DATE,
    LENGTH INTEGER, --PAGES FOR BOOK, MINUTES FOR MOVIE - UI CAN TRANSLATE TO ACTUAL TIME HH:MM AS NEEDED
    UOMID INTEGER, --FK UOM TABLE - PAGES/MINUTES
    PRIMARY KEY (ID)
);

CREATE TABLE TYPECODES (
    ID INTEGER,
    DESCRIPT VARCHAR(10),
    PRIMARY KEY (ID)
);

CREATE TABLE SERIES (
    ID INTEGER,
    DESCRIPT VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE UOM (
    ID INTEGER,
    DESCRIPT VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE GENRE (
    ID INTEGER,
    DESCRIPT VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ENTITY (
    ID INTEGER,
    DESCRIPT VARCHAR(50) NOT NULL,
    TYPEID INTEGER,
    PRIMARY KEY (ID)
);

CREATE TABLE PEOPLE (
    ID INTEGER,
    FIRSTNAME VARCHAR(25),
    LASTNAME VARCHAR(25),
    PRIMARY KEY (ID)
);

CREATE TABLE ITEMGENRE (
    ITEMID INTEGER NOT NULL,
    GENREID INTEGER NOT NULL,
    ORDERID INTEGER,
    UNIQUE (ITEMID, GENREID)
);

CREATE TABLE PRODUCTION (
    ITEMID INTEGER NOT NULL,
    ENTITYID INTEGER NOT NULL,
    ORDERID INTEGER,
    UNIQUE (ITEMID, ENTITYID)
);

CREATE TABLE PLATFORM (
    ITEMID INTEGER NOT NULL,
    ENTITYID INTEGER NOT NULL,
    ORDERID INTEGER,
    UNIQUE (ITEMID, ENTITYID)
);

CREATE TABLE AUTHOR (
    ITEMID INTEGER NOT NULL,
    PEOPLEID INTEGER NOT NULL,
    ORDERID INTEGER,
    UNIQUE (ITEMID, PEOPLEID)
);