DROP GENERATOR GEN_ITEM_ID;
DROP GENERATOR GEN_SERIES_ID;
DROP GENERATOR GEN_GENRE_ID;
DROP GENERATOR GEN_ENTITY_ID;
DROP GENERATOR GEN_PEOPLE_ID;

CREATE SEQUENCE GEN_ITEM_ID START WITH 1 INCREMENT BY 1;
GRANT USAGE ON SEQUENCE GEN_ITEM_ID TO "PUBLIC";

CREATE SEQUENCE GEN_SERIES_ID START WITH 1 INCREMENT BY 1;
GRANT USAGE ON SEQUENCE GEN_SERIES_ID TO "PUBLIC";

CREATE SEQUENCE GEN_GENRE_ID START WITH 1 INCREMENT BY 1;
GRANT USAGE ON SEQUENCE GEN_GENRE_ID TO "PUBLIC";

CREATE SEQUENCE GEN_ENTITY_ID START WITH 1 INCREMENT BY 1;
GRANT USAGE ON SEQUENCE GEN_ENTITY_ID TO "PUBLIC";

CREATE SEQUENCE GEN_PEOPLE_ID START WITH 1 INCREMENT BY 1;
GRANT USAGE ON SEQUENCE GEN_PEOPLE_ID TO "PUBLIC";