/* MAY NOT NEED ANY OF THIS!!! */
/* I ALSO CHANGED THE GENERATORS TO HAVE NAMES LIKE GEN_ITEM_ID INSTEAD OF SYSTEMITEMNUM
/*
DROP PROCEDURE SYSTEMENTITYID;
DROP PROCEDURE SYSTEMGENREID;
DROP PROCEDURE SYSTEMITEMID;
DROP PROCEDURE SYSTEMPEOPLEID;
DROP PROCEDURE SYSTEMSERIESID;

SET TERM !! ;

CREATE OR ALTER PROCEDURE SYSTEMITEMID
RETURNS (SEQNO INTEGER)
AS
BEGIN
    SEQNO = GEN_ID(SYSTEMITEMNUM,1);
END!!

SET TERM ; !!

GRANT USAGE ON SEQUENCE SYSTEMITEMNUM TO PROCEDURE SYSTEMITEMID;


SET TERM !! ;

CREATE OR ALTER PROCEDURE SYSTEMSERIESID
RETURNS (SEQNO INTEGER)
AS
BEGIN
    SEQNO = GEN_ID(SYSTEMSERIESNUM,1);
END!!

SET TERM ; !!

GRANT USAGE ON SEQUENCE SYSTEMSERIESNUM TO PROCEDURE SYSTEMSERIESID;


SET TERM !! ;

CREATE OR ALTER PROCEDURE SYSTEMGENREID
RETURNS (SEQNO INTEGER)
AS
BEGIN
    SEQNO = GEN_ID(SYSTEMGENRENUM,1);
END!!

SET TERM ; !!

GRANT USAGE ON SEQUENCE SYSTEMGENRENUM TO PROCEDURE SYSTEMGENREID;


SET TERM !! ;

CREATE OR ALTER PROCEDURE SYSTEMENTITYID
RETURNS (SEQNO INTEGER)
AS
BEGIN
    SEQNO = GEN_ID(SYSTEMENTITYNUM,1);
END!!

SET TERM ; !!

GRANT USAGE ON SEQUENCE SYSTEMENTITYNUM TO PROCEDURE SYSTEMENTITYID;


SET TERM !! ;

CREATE OR ALTER PROCEDURE SYSTEMPEOPLEID
RETURNS (SEQNO INTEGER)
AS
BEGIN
    SEQNO = GEN_ID(SYSTEMPEOPLENUM,1);
END!!

SET TERM ; !!

GRANT USAGE ON SEQUENCE SYSTEMPEOPLENUM TO PROCEDURE SYSTEMPEOPLEID;

*/