ALTER TABLE USERLIST ADD OVERRIDE INTEGER;
ALTER TABLE USERLIST ALTER COLUMN OVERRIDE POSITION 8;
ALTER TABLE USERLIST ALTER COLUMN OVERRIDE SET DEFAULT 0;

SET TERM !! ;

CREATE OR ALTER TRIGGER USERLIST_INSERT FOR USERLIST
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.USERID IS NULL) THEN EXCEPTION FIELD_REQUIRED 'UserId is required.';
  IF (NEW.DESCRIPT IS NULL OR TRIM(NEW.DESCRIPT) = '') THEN EXCEPTION FIELD_REQUIRED 'List Name is required.';
  IF (NEW.TYPEID IS NULL) THEN EXCEPTION FIELD_REQUIRED 'Media Type is required.';  
  IF (NEW.LISTTYPEID IS NULL) THEN EXCEPTION FIELD_REQUIRED 'ListTypeId is required.';

  IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_USERLIST_ID,1);
  IF (NEW.OVERRIDE IS NULL) THEN NEW.OVERRIDE = 0;
  IF (NEW.LONGDESCRIPT IS NULL OR TRIM(NEW.LONGDESCRIPT) = '') THEN NEW.LONGDESCRIPT = '';
  IF (NEW.ISPRIVATE IS NULL) THEN NEW.ISPRIVATE = 0;
  NEW.CREATEDON = CURRENT_TIMESTAMP;
  NEW.MODIFIEDON = CURRENT_TIMESTAMP;
END
!!

CREATE OR ALTER TRIGGER USERLIST_UPDATE FOR USERLIST
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
  IF (NEW.USERID IS DISTINCT FROM OLD.USERID) THEN EXCEPTION GOT_HERE 'Cannot change UserId.';
  IF (NEW.TYPEID IS DISTINCT FROM OLD.TYPEID) THEN EXCEPTION GOT_HERE 'Cannot change Media Type.';
  IF (NEW.LISTTYPEID IS DISTINCT FROM OLD.LISTTYPEID) THEN EXCEPTION GOT_HERE 'Cannot change List Type.';
  IF (NEW.CREATEDON IS DISTINCT FROM OLD.CREATEDON) THEN EXCEPTION GOT_HERE 'Cannot change Created On Date.';

  IF (OLD.LISTTYPEID > 1) THEN BEGIN
    IF (NEW.DESCRIPT IS DISTINCT FROM OLD.DESCRIPT) THEN EXCEPTION GOT_HERE 'Cannot change List Name.';
    IF (NEW.LONGDESCRIPT IS DISTINCT FROM OLD.LONGDESCRIPT) THEN EXCEPTION GOT_HERE 'Cannot change List Description.';
  END
  
  IF (NEW.DESCRIPT IS NULL OR TRIM(NEW.DESCRIPT) = '') THEN EXCEPTION FIELD_REQUIRED 'List Name is required.';

  IF (NEW.OVERRIDE IS NULL) THEN NEW.OVERRIDE = 0;
  IF (NEW.LONGDESCRIPT IS NULL OR TRIM(NEW.LONGDESCRIPT) = '') THEN NEW.LONGDESCRIPT = '';
  IF (NEW.ISPRIVATE IS NULL) THEN NEW.ISPRIVATE = 0;
  NEW.MODIFIEDON = CURRENT_TIMESTAMP;

  
  IF (NEW.OVERRIDE = -999) THEN BEGIN /* User account deleted, allow deletion of default lists */
    DELETE FROM USERLIST WHERE ID = OLD.ID;
    EXIT;
  END ELSE BEGIN /* Reset override */
    NEW.OVERRIDE = 0;
  END
END
!!

CREATE OR ALTER TRIGGER USERLIST_DELETE FOR USERLIST
ACTIVE BEFORE DELETE POSITION 0
AS
BEGIN
  IF (OLD.LISTTYPEID > 1) THEN BEGIN /* Is Default List */
    IF (OLD.OVERRIDE = 0) THEN BEGIN /* Do not allow delete */
      EXCEPTION GOT_HERE 'Cannot delete Default Lists.';
    END ELSE BEGIN                   /* Allow delete if override <> 0 */
      DELETE FROM USERLISTITEMS WHERE USERLISTID = OLD.ID;
    END
  END ELSE BEGIN
    DELETE FROM USERLISTITEMS WHERE USERLISTID = OLD.ID;
  END
END
!!

CREATE OR ALTER TRIGGER USERS_DELETE FOR USERS
ACTIVE BEFORE DELETE POSITION 0
AS
BEGIN
  UPDATE USERLIST SET OVERRIDE = -999 WHERE USERID = OLD.ID;  /* DELETES BOTH THE LIST AND LIST ITEMS */
  DELETE FROM ACTIVITY    WHERE USERID = OLD.ID;
  DELETE FROM DAILYLOG    WHERE USERID = OLD.ID;
  DELETE FROM USERRATINGS WHERE USERID = OLD.ID;
END
!!

SET TERM ; !!

