--not implemented yet 09/05/2025
--will be rewritten and run later

ALTER TABLE DAILYLOG ADD ACTIVITYLINKID INTEGER;
ALTER TABLE DAILYLOG ALTER COLUMN ACTIVITYLINKID POSITION 4;
ALTER TABLE DAILYLOG ADD CREATEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE DAILYLOG ADD MODIFIEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

SET TERM !! ;

/* Trigger: DAILYLOG_INSERT */
CREATE OR ALTER TRIGGER DAILYLOG_INSERT FOR DAILYLOG
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.USERID IS NULL) THEN EXCEPTION FIELD_REQUIRED 'UserId is required.';
  IF (NEW.TITLEID IS NULL) THEN EXCEPTION FIELD_REQUIRED 'TitleId is required.';
  IF (NEW.ACTIVITYDATE IS NULL) THEN EXCEPTION FIELD_REQUIRED 'Activity Date is required.';
  IF (NEW.PROGRESS > 0 AND NEW.UOMID IS NULL) THEN EXCEPTION FIELD_REQUIRED 'Unit of Measure is required.';

  IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_DAILYLOG_ID,1);
  IF (NEW.ACTIVITYLINKID IS NULL) THEN NEW.ACTIVITYLINKID = 0;
  IF (NEW.COMMENT IS NULL OR TRIM(NEW.COMMENT) = '') THEN NEW.COMMENT = '';
  NEW.CREATEDON = CURRENT_TIMESTAMP;
  NEW.MODIFIEDON = CURRENT_TIMESTAMP;
END
!!

/* Trigger: DAILYLOG_UPDATE */
CREATE OR ALTER TRIGGER DAILYLOG_UPDATE FOR DAILYLOG
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
  IF (NEW.USERID IS DISTINCT FROM OLD.USERID) THEN EXCEPTION GOT_HERE 'Cannot change UserId.';
  IF (NEW.TITLEID IS DISTINCT FROM OLD.TITLEID) THEN EXCEPTION GOT_HERE 'Cannot change Title.';
  IF (NEW.ACTIVITYLINKID IS DISTINCT FROM OLD.ACTIVITYLINKID) THEN EXCEPTION GOT_HERE 'Cannot change Activity LinkId.';
  IF (NEW.CREATEDON IS DISTINCT FROM OLD.CREATEDON) THEN EXCEPTION GOT_HERE 'Cannot change Created On Date.';
  IF (NEW.ACTIVITYDATE IS NULL) THEN EXCEPTION FIELD_REQUIRED 'Activity Date is required.';
  IF (NEW.PROGRESS > 0 AND NEW.UOMID IS NULL) THEN EXCEPTION FIELD_REQUIRED 'Unit of Measure is required.';

  IF (NEW.COMMENT IS NULL OR TRIM(NEW.COMMENT) = '') THEN NEW.COMMENT = '';
  NEW.MODIFIEDON = CURRENT_TIMESTAMP;
END
!!

SET TERM ; !!

CREATE INDEX DAILYLOG_USER_DATE ON DAILYLOG (USERID, ACTIVITYDATE);
CREATE INDEX DAILYLOG_ACTIVITYLINK ON DAILYLOG (ACTIVITYLINKID);