/* COMMENTED OUT ISPRIVATE FROM USERLIST TRIGGERS */
  ALTER TABLE USERLIST ALTER ISPRIVATE TO ISPRIVATE_NEW;

  ALTER TABLE USERLIST ADD ISPRIVATE SMALLINT;
  ALTER TABLE USERLIST ALTER COLUMN ISPRIVATE POSITION 6;

  UPDATE USERLIST
  SET ISPRIVATE = ISPRIVATE_NEW;

  ALTER TABLE USERLIST DROP ISPRIVATE_NEW;
/* UN-COMMENT ISPRIVATE FROM USERLIST TRIGGERS */

/* COMMENTED OUT ISENTERTAINMENT AND ISBOOK FROM GENRE TRIGGERS */
  ALTER TABLE GENRE ALTER ISENTERTAINMENT TO ISENTERTAINMENT_NEW;
  ALTER TABLE GENRE ALTER ISBOOK TO ISBOOK_NEW;

  ALTER TABLE GENRE ADD ISENTERTAINMENT SMALLINT;
  ALTER TABLE GENRE ALTER COLUMN ISENTERTAINMENT POSITION 5;
  ALTER TABLE GENRE ADD ISBOOK SMALLINT;
  ALTER TABLE GENRE ALTER COLUMN ISBOOK POSITION 6;

  UPDATE GENRE
  SET ISENTERTAINMENT = ISENTERTAINMENT_NEW,
    ISBOOK = ISBOOK_NEW;

  ALTER TABLE GENRE DROP ISENTERTAINMENT_NEW;
  ALTER TABLE GENRE DROP ISBOOK_NEW;
/* UN-COMMENT ISENTERTAINMENT AND ISBOOK FROM GENRE TRIGGERS */
