SET TERM !! ;

CREATE OR ALTER TRIGGER ACTIVITY_UPDATE FOR ACTIVITY
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
  IF (NEW.USERID IS DISTINCT FROM OLD.USERID) THEN EXCEPTION GOT_HERE 'Cannot change UserId.';
  IF (NEW.TITLEID IS DISTINCT FROM OLD.TITLEID) THEN EXCEPTION GOT_HERE 'Cannot change Title.';  
  IF (NEW.CREATEDON IS DISTINCT FROM OLD.CREATEDON) THEN EXCEPTION GOT_HERE 'Cannot change Created On Date.';
  IF (NEW.STARTDATE IS NULL AND NEW.FINISHDATE IS NULL) THEN EXCEPTION FIELD_REQUIRED 'Start or Finish Date is required.';

  IF (NEW.FINISHDATE IS NULL) THEN
    NEW.COMPLETED = 0;
  ELSE BEGIN
    NEW.COMPLETED = 1;
    IF (NEW.STARTDATE IS NULL) THEN NEW.STARTDATE = NEW.FINISHDATE;
  END

  IF (NEW.NOTES IS NULL OR TRIM(NEW.NOTES) = '') THEN NEW.NOTES = '';
  NEW.MODIFIEDON = CURRENT_TIMESTAMP;
END
!!

CREATE OR ALTER TRIGGER DAILYLOG_UPDATE FOR DAILYLOG
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
  IF (NEW.USERID IS DISTINCT FROM OLD.USERID) THEN EXCEPTION GOT_HERE 'Cannot change UserId.';
  IF (NEW.TITLEID IS DISTINCT FROM OLD.TITLEID) THEN EXCEPTION GOT_HERE 'Cannot change Title.';  
  IF (NEW.ACTIVITYDATE IS NULL) THEN EXCEPTION FIELD_REQUIRED 'Activity Date is required.';
  IF (NEW.PROGRESS > 0 AND NEW.UOMID IS NULL) THEN EXCEPTION FIELD_REQUIRED 'Unit of Measure is required.';

  IF (NEW.COMMENT IS NULL OR TRIM(NEW.COMMENT) = '') THEN NEW.COMMENT = '';
END
!!

CREATE OR ALTER TRIGGER GENRE_UPDATE FOR GENRE
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
  IF (NEW.DESCRIPT IS NULL OR TRIM(NEW.DESCRIPT) = '') THEN EXCEPTION FIELD_REQUIRED 'Genre Name is required.';

  IF (NEW.ISENTERTAINMENT IS NULL) THEN NEW.ISENTERTAINMENT = 0;
  IF (NEW.ISBOOK IS NULL) THEN NEW.ISBOOK = 0;
END
!!

CREATE OR ALTER TRIGGER SERIES_DELETE FOR SERIES
ACTIVE BEFORE DELETE POSITION 0
AS
BEGIN
  UPDATE TITLE SET SERIESID = NULL, ORDERID = NULL WHERE SERIESID = OLD.ID;
END
!!

CREATE OR ALTER TRIGGER TITLE_UPDATE FOR TITLE
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
  IF (NEW.DESCRIPT IS NULL OR TRIM(NEW.DESCRIPT) = '') THEN EXCEPTION FIELD_REQUIRED 'Title is required.';
  IF (NEW.TYPEID IS NULL) THEN EXCEPTION FIELD_REQUIRED 'Media Type is required.';
  IF (NEW.CONTENT_SIZE > 0 AND NEW.UOMID IS NULL) THEN EXCEPTION FIELD_REQUIRED 'Unit of Measure is required.';

  IF (NEW.CONTENT_SIZE IS NULL) THEN NEW.CONTENT_SIZE = 0;
  IF (NEW.IMAGEFILE IS NULL) THEN NEW.IMAGEFILE = '';
END
!!

CREATE OR ALTER TRIGGER TITLE_DELETE FOR TITLE
ACTIVE BEFORE DELETE POSITION 0
AS
BEGIN
  IF (EXISTS(SELECT * FROM ACTIVITY       WHERE TITLEID = OLD.ID)) THEN EXCEPTION DATA_LINKED;
  IF (EXISTS(SELECT * FROM DAILYLOG       WHERE TITLEID = OLD.ID)) THEN EXCEPTION DATA_LINKED;
  IF (EXISTS(SELECT * FROM USERLISTITEMS  WHERE TITLEID = OLD.ID)) THEN EXCEPTION DATA_LINKED;
  IF (EXISTS(SELECT * FROM USERRATINGS    WHERE TITLEID = OLD.ID)) THEN EXCEPTION DATA_LINKED;
END
!!

CREATE OR ALTER TRIGGER USERLISTITEMS_UPDATE FOR USERLISTITEMS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
  IF (NEW.USERLISTID IS DISTINCT FROM OLD.USERLISTID) THEN EXCEPTION GOT_HERE 'Cannot change UserList.';
  IF (NEW.TITLEID IS DISTINCT FROM OLD.TITLEID) THEN EXCEPTION GOT_HERE 'Cannot change Title.';    
  IF (NEW.CREATEDON IS DISTINCT FROM OLD.CREATEDON) THEN EXCEPTION GOT_HERE 'Cannot change Created On Date.';

  IF (NEW.SORTORDER IS NULL) THEN NEW.SORTORDER = 0;
END
!!

CREATE OR ALTER TRIGGER USERRATINGS_UPDATE FOR USERRATINGS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
  IF (NEW.USERID IS DISTINCT FROM OLD.USERID) THEN EXCEPTION GOT_HERE 'Cannot change UserId.';
  IF (NEW.TITLEID IS DISTINCT FROM OLD.TITLEID) THEN EXCEPTION GOT_HERE 'Cannot change Title.';  
  IF (NEW.CREATEDON IS DISTINCT FROM OLD.CREATEDON) THEN EXCEPTION GOT_HERE 'Cannot change Created On Date.';
  IF (NEW.RATING IS NULL) THEN EXCEPTION FIELD_REQUIRED 'Rating is required.';
  IF (NEW.RATING < 0 OR NEW.RATING > 5) THEN EXCEPTION GOT_HERE 'Rating must be 0 to 5.';

  IF (NEW.REVIEW IS NULL OR TRIM(NEW.REVIEW) = '') THEN NEW.REVIEW = '';
  IF (NEW.HIDE IS NULL) THEN NEW.HIDE = 0;
  NEW.MODIFIEDON = CURRENT_TIMESTAMP;
END
!!

CREATE OR ALTER TRIGGER USERS_UPDATE FOR USERS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
  IF (NEW.FIRSTNAME IS NULL OR TRIM(NEW.FIRSTNAME) = '') THEN EXCEPTION FIELD_REQUIRED 'First Name is required.';
  IF (NEW.LASTNAME IS NULL OR TRIM(NEW.LASTNAME) = '') THEN EXCEPTION FIELD_REQUIRED 'Last Name is required.';
  IF (NEW.USERNAME IS NULL OR TRIM(NEW.USERNAME) = '') THEN EXCEPTION FIELD_REQUIRED 'Username is required.';
  IF (NEW.PASSWORD_HASH IS NULL OR TRIM(NEW.PASSWORD_HASH) = '') THEN EXCEPTION FIELD_REQUIRED 'Password is required.';
  IF (NEW.CREATEDON IS DISTINCT FROM OLD.CREATEDON) THEN EXCEPTION GOT_HERE 'Cannot change Created On Date.';
  
  IF (NEW.EMAIL IS NULL OR TRIM(NEW.EMAIL) = '') THEN NEW.EMAIL = '';
  NEW.MODIFIEDON = CURRENT_TIMESTAMP;
END
!!

CREATE OR ALTER TRIGGER USERS_DELETE FOR USERS
ACTIVE BEFORE DELETE POSITION 0
AS
BEGIN
  DELETE FROM USERLIST    WHERE USERID = OLD.ID;  /* DELETES BOTH THE LIST AND LIST ITEMS */
  DELETE FROM ACTIVITY    WHERE USERID = OLD.ID;
  DELETE FROM DAILYLOG    WHERE USERID = OLD.ID;
  DELETE FROM USERRATINGS WHERE USERID = OLD.ID;
END
!!

SET TERM ; !!