DESCRIPT = VARCHAR 80
LONGDESCRIPT = VARCHAR 255
NOTE = VARCHAR 6144
REFFERENCE = VARCHAR 10
COMMENT = VARCHAR 50



ALTER TABLE ACTIVITY ADD STATUSID INTEGER;
ALTER TABLE ACTIVITY ALTER COLUMN STATUSID POSITION 4;
ALTER TABLE ACTIVITY ADD DNF SMALLINT;
ALTER TABLE ACTIVITY ALTER COLUMN DNF POSITION 8;
ALTER TABLE ACTIVITY ADD DNFON TIMESTAMP;
ALTER TABLE ACTIVITY ALTER COLUMN DNFON POSITION 9;
ALTER TABLE ACTIVITY ADD REVIEWED SMALLINT;
ALTER TABLE ACTIVITY ALTER COLUMN REVIEWED POSITION 10;
ALTER TABLE ACTIVITY ADD REVIEWEDON TIMESTAMP;
ALTER TABLE ACTIVITY ALTER COLUMN REVIEWEDON POSITION 11;
ALTER TABLE ACTIVITY ADD RATING DOUBLE PRECISION;
ALTER TABLE ACTIVITY ALTER COLUMN RATING POSITION 12;
ALTER TABLE ACTIVITY ADD REVIEWTEXT VARCHAR(2000);
ALTER TABLE ACTIVITY ALTER COLUMN REVIEWTEXT POSITION 13;
ALTER TABLE ACTIVITY ADD HIDEREVIEW SMALLINT;
ALTER TABLE ACTIVITY ALTER COLUMN HIDEREVIEW POSITION 14;

CREATE INDEX ACTIVITY_USER_TITLE_STATUS ON ACTIVITY (USERID, TITLEID, STATUSID);

SET TERM !! ;

CREATE OR ALTER TRIGGER ACTIVITY_INSERT FOR ACTIVITY
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.USERID IS NULL) THEN EXCEPTION FIELD_REQUIRED 'UserId is required.';
  IF (NEW.TITLEID IS NULL) THEN EXCEPTION FIELD_REQUIRED 'TitleId is required.';
  IF (NEW.STATUSID IS NULL OR NEW.STATUSID NOT BETWEEN 1 AND 4) THEN EXCEPTION FIELD_REQUIRED 'Valid StatusId (1-4) is required.';

  /* PLANNED */
  IF (NEW.STATUSID = 1) THEN BEGIN
    NEW.STARTDATE  = NULL;
    NEW.FINISHDATE = NULL;
    NEW.COMPLETED  = 0;
    NEW.DNF        = 0;
    NEW.DNFON      = NULL;
  END
  /* IN-PROGRESS */
  ELSE IF (NEW.STATUSID = 2) THEN BEGIN
    IF (NEW.STARTDATE IS NULL) THEN EXCEPTION FIELD_REQUIRED 'Start Date is required.';
    NEW.FINISHDATE = NULL;
    NEW.COMPLETED  = 0;
    NEW.DNF        = 0;
    NEW.DNFON      = NULL;
  END
  /* COMPLETED */
  ELSE IF (NEW.STATUSID = 3) THEN BEGIN
    IF (NEW.FINISHDATE IS NULL) THEN EXCEPTION FIELD_REQUIRED 'Finish Date is required.';
    IF (NEW.STARTDATE IS NULL) THEN NEW.STARTDATE = NEW.FINISHDATE;
    NEW.COMPLETED  = 1;
    NEW.DNF        = 0;
    NEW.DNFON      = NULL;
  END
  /* DID NOT FINISH */
  ELSE IF (NEW.STATUSID = 4) THEN BEGIN
    IF (NEW.STARTDATE IS NULL) THEN EXCEPTION FIELD_REQUIRED 'Start Date is required.';
    NEW.FINISHDATE = NULL;
    NEW.COMPLETED  = 0;
    NEW.DNF        = 1;
    IF (NEW.DNFON IS NULL) THEN NEW.DNFON = CURRENT_TIMESTAMP;
  END

  IF (NEW.REVIEWED = 1) THEN BEGIN
    IF (NEW.REVIEWEDON IS NULL) THEN NEW.REVIEWEDON = CURRENT_TIMESTAMP;
    IF (NEW.REVIEWTEXT IS NULL) THEN NEW.REVIEWTEXT = '';
    IF (NEW.HIDEREVIEW IS NULL) THEN NEW.HIDEREVIEW = 0;
    /* RATING: leave as provided (NULL allowed) */
  END
  ELSE BEGIN
    NEW.REVIEWED   = 0;
    NEW.REVIEWEDON = NULL;
    NEW.RATING     = NULL;
    NEW.REVIEWTEXT = '';
    NEW.HIDEREVIEW = 0;
  END

  IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_ACTIVITY_ID, 1);
  IF (NEW.NOTES IS NULL OR TRIM(NEW.NOTES) = '') THEN NEW.NOTES = '';
  NEW.CREATEDON = CURRENT_TIMESTAMP;
  NEW.MODIFIEDON = CURRENT_TIMESTAMP;
END
!!

SET TERM ; !!